apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-service
  labels:
    app: social-service
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: social-service
  template:
    metadata:
      labels:
        app: social-service
        tripplanning.io/colocate: "true"
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: tripplanning.io/colocate
                      operator: Exists
                topologyKey: kubernetes.io/hostname
      serviceAccountName: social-service
      containers:
        - name: social-service
          image: europe-west1-docker.pkg.dev/milestone2-tbd-cad/tripplanning/tripplanning-social-service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: social-service-secrets
            - configMapRef:
                name: social-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
