apiVersion: v1
kind: Service
metadata:
  name: social-service
  labels:
    app: social-service
spec:
  selector:
    app: social-service
  ports:
    - port: 8080
      targetPort: 8081
      name: http
