apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tripplanning-enterprise-redent
  namespace: tripplanning-ent-redent
  annotations:
    tripplanning.htwg.dev/values-checksum: ea083e282bceab8e32ff58af6879dd224f29f08fb280deddb2413212870aa7b7
spec:
  interval: 10m
  chart:
    spec:
      chart: ms2/charts/tripplanning
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: tripplanning-enterprise-redent-values
      valuesKey: values.yaml
