apiVersion: v1
kind: ConfigMap
metadata:
  name: tripplanning-free-values
  namespace: tripplanning-free
data:
  values.yaml: |
    services:
      trip:
        image:
          repository: ghcr.io/tbd-htwg/backend/tripplanning-trip-service
          tag: latest
          pullPolicy: Always
      social:
        image:
          repository: ghcr.io/tbd-htwg/backend/tripplanning-social-service
          tag: latest
          pullPolicy: Always
      externalInfo:
        image:
          repository: ghcr.io/tbd-htwg/backend/tripplanning-external-info-service
          tag: latest
          pullPolicy: Always
    backingServices:
      postgres:
        auth:
          existingSecret: trip-service-secrets
          passwordKey: password
    autoscaling:
      enabled: false
