global:
  tier: free
  tenantId: free
  deployment:
    environment: dev
  identityPlatform:
    tenantId: ""
  storage:
    imagesPrefix: free
  frontend:
    bucketPrefix: free
  cache:
    keyPrefix: free

apiRouter:
  mode: free
  enforceKnownHosts: false
  loadBalancer:
    enabled: false

services:
  trip:
    replicas: 1
    resources:
      requests:
        cpu: "150m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"
  social:
    replicas: 1
    resources:
      requests:
        cpu: "150m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"
  externalInfo:
    replicas: 1
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "256Mi"

autoscaling:
  enabled: false
