global:
  tier: enterprise
  tenantId: ""
  hostnames: []
  identityPlatform:
    tenantId: ""
  frontend:
    bucketName: "tbd-cloudappdev-frontend-bucket"
    bucketPrefix: ""
    brandName: "TripPlanning Enterprise"
    colorScheme: "default"
    brandIcon: ""
  storage:
    imagesBucketName: ""
    imagesPrefix: ""
  search:
    indexName: tripentity
  cache:
    keyPrefix: ""
  cloudSql:
    enabled: true
    connectionName: ""
    databaseName: tripplanning
    userName: tripplanning_app

apiRouter:
  mode: enterprise
  enforceKnownHosts: true
  tenants: []
  loadBalancer:
    enabled: true
    ip: ""
    externalTrafficPolicy: Cluster

services:
  apiRouter:
    replicas: 2
  trip:
    replicas: 2
    image:
      repository: ghcr.io/tbd-htwg/backend/tripplanning-trip-service
      tag: stable
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "500m"
        memory: "768Mi"
      limits:
        cpu: "1000m"
        memory: "1024Mi"
  social:
    replicas: 2
    image:
      repository: ghcr.io/tbd-htwg/backend/tripplanning-social-service
      tag: stable
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "200m"
        memory: "768Mi"
      limits:
        cpu: "500m"
        memory: "768Mi"
  externalInfo:
    replicas: 1
    image:
      repository: ghcr.io/tbd-htwg/backend/tripplanning-external-info-service
      tag: stable
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "150m"
        memory: "768Mi"
      limits:
        cpu: "500m"
        memory: "768Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
  trip:
    minReplicas: 2
    maxReplicas: 4
  social:
    minReplicas: 2
    maxReplicas: 4
  externalInfo:
    minReplicas: 1
    maxReplicas: 2

backingServices:
  postgres:
    enabled: false
  opensearch:
    enabled: true
    serviceName: opensearch
    resources:
      limits:
        cpu: "750m"
  valkey:
    enabled: true
