global:
  tier: standard
  tenantId: standard-shared
  hostnames: []
  identityPlatform:
    tenantId: ""
  frontend:
    bucketName: "tbd-cloudappdev-frontend-bucket"
    bucketPrefix: standard
    brandName: "TripPlanning"
    colorScheme: "default"
    brandIcon: ""
  storage:
    imagesBucketName: "tbd-cloudappdev-images-bucket"
    imagesPrefix: standard
  search:
    indexName: tripentity-standard
  cache:
    keyPrefix: std

apiRouter:
  mode: standard
  enforceKnownHosts: true
  tenants: []
  loadBalancer:
    enabled: true
    ip: ""
    externalTrafficPolicy: Cluster

services:
  apiRouter:
    replicas: 1
  trip:
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "768Mi"
      limits:
        cpu: "750m"
        memory: "1024Mi"
  social:
    replicas: 1
    resources:
      requests:
        cpu: "150m"
        memory: "768Mi"
      limits:
        cpu: "500m"
        memory: "768Mi"
  externalInfo:
    replicas: 1
    resources:
      requests:
        cpu: "100m"
        memory: "768Mi"
      limits:
        cpu: "500m"
        memory: "768Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  scaleUpStabilizationSeconds: 60
  scaleDownStabilizationSeconds: 300
  trip:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 0
  social:
    minReplicas: 1
    maxReplicas: 2
  externalInfo:
    minReplicas: 1
    maxReplicas: 2

backingServices:
  postgres:
    enabled: false
  opensearch:
    enabled: true
    resources:
      limits:
        cpu: "400m"
  valkey:
    enabled: true
