apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tripplanning-enterprise-one-cloud-away
  namespace: tripplanning-ent-one-cloud-away
  annotations:
    tripplanning.htwg.dev/values-checksum: 2ab07314f89caee13bb08824ac327152230468c5d120995f047530a320abbd92
spec:
  interval: 10m
  chart:
    spec:
      chart: ms2/charts/tripplanning
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: tripplanning-enterprise-one-cloud-away-values
      valuesKey: values.yaml
