apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tripplanning-enterprise-one-cloud-away
  namespace: tripplanning-ent-one-cloud-away
  annotations:
    tripplanning.htwg.dev/values-checksum: 1a6f79dc1ca85f1f0285e414f3c7cf01e2a2e39623ccefc01f6e7c96cb9e232a
spec:
  interval: 10m
  chart:
    spec:
      chart: ms2/charts/tripplanning
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: tripplanning-enterprise-one-cloud-away-values
      valuesKey: values.yaml
