apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: flux-system
data:
  GCP_PROJECT_ID: tbd-cloudappdev
  GCP_REGION: europe-west1
  FIRESTORE_DATABASE_ID: tbd-firestore
  FRONTEND_BUCKET: tbd-cloudappdev-frontend-bucket
  IMAGES_BUCKET: tbd-cloudappdev-images-bucket
  STANDARD_LB_IP: 34.140.254.45
