apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform-kustomization.yaml
  - platform-config-kustomization.yaml
  - platform-gateway-kustomization.yaml
  - tenants-kustomization.yaml
