apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: milestone2-tbd-cad
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: tripplanning-gke
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
