apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tripplanning-enterprise-finalent
  namespace: tripplanning-ent-finalent
  annotations:
    tripplanning.htwg.dev/values-checksum: e3c66e7fba5a1bdbcf9e1b84c94b3f3a4d4c0806961d762fae33aaf6d7b5c2d5
spec:
  interval: 10m
  chart:
    spec:
      chart: ms2/charts/tripplanning
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: tripplanning-enterprise-finalent-values
      valuesKey: values.yaml
