apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-info-service
  labels:
    app: external-info-service
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-info-service
  template:
    metadata:
      labels:
        app: external-info-service
        tripplanning.io/colocate: "true"
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: tripplanning.io/colocate
                      operator: Exists
                topologyKey: kubernetes.io/hostname
      containers:
        - name: external-info-service
          image: europe-west1-docker.pkg.dev/milestone2-tbd-cad/tripplanning/tripplanning-external-info-service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: external-info-service-secrets
            - configMapRef:
                name: external-info-service-config
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 300m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
