{{- if and .Values.backingServices.postgres.enabled (not .Values.backingServices.postgres.auth.existingSecret) (ne .Values.backingServices.postgres.auth.password "") }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "tripplanning.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
stringData:
  {{ .Values.backingServices.postgres.auth.passwordKey }}: {{ .Values.backingServices.postgres.auth.password | quote }}
{{- end }}
