{{- if .Values.backingServices.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backingServices.redis.serviceName }}
  labels:
    {{- include "tripplanning.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  selector:
    app.kubernetes.io/component: redis
    {{- include "tripplanning.selectorLabels" . | nindent 4 }}
  ports:
    - port: 6379
      targetPort: 6379
{{- end }}
