{{- if .Values.backingServices.valkey.enabled }}
{{- $rollingUpdate := default dict .Values.backingServices.valkey.rollingUpdate }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  labels:
    {{- include "tripplanning.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ default 0 $rollingUpdate.maxSurge }}
      maxUnavailable: {{ default 1 $rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: valkey
      {{- include "tripplanning.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: valkey
        {{- include "tripplanning.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: valkey
          image: {{ .Values.backingServices.valkey.image }}
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: {{ .Values.backingServices.valkey.resources.requests.cpu }}
              memory: {{ .Values.backingServices.valkey.resources.requests.memory }}
            limits:
              cpu: {{ .Values.backingServices.valkey.resources.limits.cpu }}
              memory: {{ .Values.backingServices.valkey.resources.limits.memory }}
{{- end }}
