apiVersion: v1
kind: Service
metadata:
  name: api-router
  labels:
    {{- include "tripplanning.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-router
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"{{ .Values.services.apiRouter.port }}":{}}}'
spec:
  selector:
    app.kubernetes.io/component: api-router
    {{- include "tripplanning.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.services.apiRouter.port }}
      targetPort: {{ .Values.services.apiRouter.port }}
