apiVersion: v1
kind: Service
metadata:
  name: trip-service
  labels:
    {{- include "tripplanning.labels" . | nindent 4 }}
    app.kubernetes.io/component: trip-service
  {{- if .Values.services.trip.neg.enabled }}
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"{{ .Values.services.trip.port }}":{}}}'
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: trip-service
    {{- include "tripplanning.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.services.trip.port }}
      targetPort: {{ .Values.services.trip.port }}
