apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trip-service-db-secrets
  namespace: tripplanning-standard
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: trip-service-db-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: tripplanning-standard-blue5-db-password
