apiVersion: v1
kind: ConfigMap
metadata:
  name: tripplanning-standard-generated-tenants
  namespace: tripplanning-standard
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    apiRouter:
      tenants:
      - tenantId: tripper-ultimate
        identityPlatformTenantId: tripper-ultimate-eqeid
        hostnames:
        - tripper-ultimate.k8s.tbd-htwg.de
      - tenantId: xtripmanager
        identityPlatformTenantId: xtripmanager-j058b
        hostnames:
        - xtripmanager.k8s.tbd-htwg.de
      loadBalancer:
        ip: ''
    global:
      cloudSql:
        enabled: true
        connectionName: ''
        databaseName: tripplanning_std_tripper_ultimate
        userName: tripplanning_app_tripper_ultimate
      search:
        indexName: tripentity-tripper-ultimate
      cache:
        keyPrefix: std:tripper-ultimate
      storage:
        imagesPrefix: standard/tripper-ultimate
    services:
      trip:
        secretRefs:
        - trip-service-secrets
        - trip-service-db-secrets
        env:
          CORS_ALLOWED_ORIGINS: https://k8s.tbd-htwg.de,https://tripper-ultimate.k8s.tbd-htwg.de,https://xtripmanager.k8s.tbd-htwg.de
          TRIPPLANNING_TENANT_DATASOURCE_ROUTING: 'true'
          TRIPPLANNING_PLATFORM_BASE_URL: http://platform-service.tripplanning-system:8083
      social:
        env:
          CORS_ALLOWED_ORIGINS: https://k8s.tbd-htwg.de,https://tripper-ultimate.k8s.tbd-htwg.de,https://xtripmanager.k8s.tbd-htwg.de
      externalInfo:
        env:
          CORS_ALLOWED_ORIGINS: https://k8s.tbd-htwg.de,https://tripper-ultimate.k8s.tbd-htwg.de,https://xtripmanager.k8s.tbd-htwg.de
