apiVersion: v1
kind: ConfigMap
metadata:
  name: tripplanning-standard-generated-tenants
  namespace: tripplanning-standard
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    apiRouter:
      tenants:
      - tenantId: firststand
        identityPlatformTenantId: first-standard-aqvo9
        hostnames:
        - firststand.k8s.tbd-htwg.de
      loadBalancer:
        ip: 34.79.13.109
    global:
      cloudSql:
        enabled: true
        connectionName: tbd-cloudappdev:europe-west1:tripplanning-standard
        databaseName: tripplanning_std_firststand
        userName: tripplanning_app_firststand
      search:
        indexName: tripentity-firststand
      cache:
        keyPrefix: std:firststand
      storage:
        imagesPrefix: standard/firststand
    services:
      trip:
        secretRefs:
        - trip-service-secrets
        - trip-service-db-secrets
        env:
          CORS_ALLOWED_ORIGINS: https://k8s.tbd-htwg.de,https://firststand.k8s.tbd-htwg.de
          TRIPPLANNING_TENANT_DATASOURCE_ROUTING: 'false'
          TRIPPLANNING_PLATFORM_BASE_URL: http://platform-service.tripplanning-system:8083
      social:
        env:
          CORS_ALLOWED_ORIGINS: https://k8s.tbd-htwg.de,https://firststand.k8s.tbd-htwg.de
      externalInfo:
        env:
          CORS_ALLOWED_ORIGINS: https://k8s.tbd-htwg.de,https://firststand.k8s.tbd-htwg.de
