apiVersion: v1
kind: ConfigMap
metadata:
  name: tripplanning-standard-generated-tenants
  namespace: tripplanning-standard
data:
  values.yaml: |
    apiRouter:
      tenants:
      - tenantId: test03
        identityPlatformTenantId: test03-tj13t
        hostnames:
        - test03.k8s.tbd-htwg.de
      loadBalancer:
        ip: 34.52.217.31
