apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tripplanning-enterprise-ente
  namespace: tripplanning-ent-ente
  annotations:
    tripplanning.htwg.dev/values-checksum: 4330f0827f9f5211522acbceb150d15afe29ec026bdfeb7a7d0415465aa9d0ab
spec:
  interval: 10m
  chart:
    spec:
      chart: ms2/charts/tripplanning
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: tripplanning-enterprise-ente-values
      valuesKey: values.yaml
