apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tripplanning-enterprise-ente
  namespace: tripplanning-ent-ente
  annotations:
    tripplanning.htwg.dev/values-checksum: d2695d68e3e09dbf4964b680a0ff7cb201cadc6179cbe3b82285fd25eb39ee4d
spec:
  interval: 10m
  chart:
    spec:
      chart: ms2/charts/tripplanning
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: tripplanning-enterprise-ente-values
      valuesKey: values.yaml
