tenantId: enteentegans
tier: enterprise
projectId: tbd-cloudappdev
namespace: tripplanning-ent-enteentegans
hostnames:
- enteentegans.enterprise.k8s.tbd-htwg.de
identityPlatform:
  displayName: enteentegans
  emailPasswordEnabled: true
  mfaEnabled: true
  tenantId: enteentegans-r1d2p
frontend:
  bucketPrefix: enterprise/enteentegans
  brandName: EnteEnteGans
  colorScheme: default
  brandIcon: assets/brand-icon.png
database:
  cloudSqlInstance: tripplanning-ent-enteentegans
  databaseName: tripplanning
  userName: tripplanning_app
storage:
  imageBucketName: tbd-cloudappdev-enteentegans-images-bucket
search:
  releaseName: opensearch-enteentegans
cache:
  dedicated: true
services:
  trip:
    image:
      tag: latest
      pullPolicy: Always
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
  social:
    image:
      tag: latest
      pullPolicy: Always
    replicas: 1
    resources:
      limits:
        cpu: 750m
        memory: 768Mi
      requests:
        cpu: 50m
        memory: 384Mi
  externalInfo:
    image:
      tag: latest
      pullPolicy: Always
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
  customfield:
    enabled: true
    image:
      tag: latest
      pullPolicy: Always
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
autoscaling:
  enabled: true
  trip:
    minReplicas: 1
    maxReplicas: 4
  social:
    minReplicas: 1
    maxReplicas: 3
  externalInfo:
    minReplicas: 2
    maxReplicas: 3
  customfield:
    minReplicas: 1
    maxReplicas: 3
