tenantId: finalent
tier: enterprise
projectId: tbd-cloudappdev
namespace: tripplanning-ent-finalent
hostnames:
- finalent.enterprise.k8s.tbd-htwg.de
identityPlatform:
  displayName: finalent
  emailPasswordEnabled: true
  mfaEnabled: true
  tenantId: finalent-q8c16
frontend:
  bucketPrefix: enterprise/finalent
  brandName: Final Enterprise
  colorScheme: default
  brandIcon: assets/brand-icon.png
database:
  cloudSqlInstance: tripplanning-ent-finalent
  databaseName: tripplanning
  userName: tripplanning_app
storage:
  imageBucketName: tbd-cloudappdev-finalent-images-bucket
search:
  releaseName: opensearch-finalent
cache:
  dedicated: true
services:
  trip:
    image:
      tag: latest
      pullPolicy: Always
  social:
    image:
      tag: latest
      pullPolicy: Always
  externalInfo:
    image:
      tag: latest
      pullPolicy: Always
  customfield:
    enabled: true
    image:
      tag: latest
      pullPolicy: Always
