tenantId: redent
tier: enterprise
projectId: tbd-cloudappdev
namespace: tripplanning-ent-redent
hostnames:
- redent.enterprise.k8s.tbd-htwg.de
identityPlatform:
  displayName: redent
  emailPasswordEnabled: true
  mfaEnabled: true
  tenantId: redent-iw5b2
frontend:
  bucketPrefix: enterprise/redent
  brandName: Red Enterprise
  colorScheme: default
  brandIcon: assets/brand-icon.png
database:
  cloudSqlInstance: tripplanning-ent-redent
  databaseName: tripplanning
  userName: tripplanning_app
storage:
  imageBucketName: tbd-cloudappdev-redent-images-bucket
search:
  releaseName: opensearch-redent
cache:
  dedicated: true
services:
  trip:
    image:
      tag: latest
      pullPolicy: Always
    replicas: 1
    resources:
      limits:
        cpu: 1500m
        memory: 1536Mi
      requests:
        cpu: 600m
        memory: 768Mi
  social:
    image:
      tag: latest
      pullPolicy: Always
    replicas: 1
    resources:
      limits:
        cpu: 750m
        memory: 768Mi
      requests:
        cpu: 50m
        memory: 384Mi
  externalInfo:
    image:
      tag: latest
      pullPolicy: Always
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
  customfield:
    enabled: true
    image:
      tag: latest
      pullPolicy: Always
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi
autoscaling:
  enabled: true
  trip:
    minReplicas: 1
    maxReplicas: 2
  social:
    minReplicas: 1
    maxReplicas: 2
  externalInfo:
    minReplicas: 1
    maxReplicas: 2
  customfield:
    minReplicas: 1
    maxReplicas: 2
