apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-service-config
  labels:
    {{- include "tripplanning.labels" . | nindent 4 }}
    app.kubernetes.io/component: trip-service
data:
{{- range $key, $value := .Values.services.trip.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
