#!/bin/bash
# GCE startup / manual: Docker + gcloud, sync compose from GCS, secrets from SM, compose up.
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

INSTALL_DIR="${INSTALL_DIR:-/opt/es-gateway}"
META_BASE="http://metadata.google.internal/computeMetadata/v1"

es_log() {
  echo "[es-bootstrap] $*"
}

dpkg_is_busy() {
  if command -v fuser >/dev/null 2>&1; then
    fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 \
      || fuser /var/lib/dpkg/lock >/dev/null 2>&1
  else
    pgrep -x apt-get >/dev/null 2>&1 || pgrep -x dpkg >/dev/null 2>&1
  fi
}

wait_for_apt_lock() {
  local max_wait="${1:-600}"
  local deadline=$((SECONDS + max_wait))
  while (( SECONDS < deadline )); do
    if dpkg_is_busy; then
      es_log "Waiting for dpkg lock..."
      sleep 5
      continue
    fi
    sleep 1
    if ! dpkg_is_busy; then
      return 0
    fi
  done
  es_log "ERROR: timed out after ${max_wait}s waiting for dpkg lock"
  return 1
}

ensure_apt_base() {
  wait_for_apt_lock
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg lsb-release apt-transport-https
}

ensure_docker() {
  if command -v docker >/dev/null 2>&1; then
    return 0
  fi
  es_log "Installing Docker Engine (get.docker.com)"
  curl -fsSL https://get.docker.com | sh
}

ensure_gcloud() {
  if command -v gsutil >/dev/null 2>&1 && command -v gcloud >/dev/null 2>&1; then
    return 0
  fi
  es_log "Installing Google Cloud CLI"
  wait_for_apt_lock
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | gpg --dearmor -o /etc/apt/keyrings/cloud.google.gpg
  echo "deb [signed-by=/etc/apt/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
    > /etc/apt/sources.list.d/google-cloud-sdk.list
  apt-get update -qq
  apt-get install -y -qq google-cloud-cli
}

ensure_apt_base
ensure_docker
ensure_gcloud

mkdir -p /var/log
exec > >(tee -a /var/log/es-bootstrap.log) 2>&1

get_attr() {
  curl -fsS -H "Metadata-Flavor: Google" "${META_BASE}/instance/attributes/$1"
}

PROJECT_ID=$(curl -fsS -H "Metadata-Flavor: Google" "${META_BASE}/project/project-id")
BUCKET=$(get_attr es_assets_bucket)
SA_SECRET=$(get_attr es_gcp_sa_secret_id)
ELASTIC_SECRET_ID=$(get_attr es_elastic_password_secret_id)
CADDY_DOMAIN=$(get_attr es_caddy_domain)
ES_JAVA_OPTS=$(get_attr es_java_opts)

es_log "Syncing stack from gs://${BUCKET}"
mkdir -p "${INSTALL_DIR}"
cd "${INSTALL_DIR}"
gsutil cp "gs://${BUCKET}/docker-compose.yml" .
gsutil cp "gs://${BUCKET}/docker-compose.gcp.yml" .
gsutil cp "gs://${BUCKET}/Caddyfile" .

ES_PASS="$(gcloud secrets versions access latest --secret="${ELASTIC_SECRET_ID}" --project="${PROJECT_ID}")"
{
  echo "# Generated by bootstrap (terraform_es)"
  echo "CADDY_DOMAIN=${CADDY_DOMAIN}"
  echo "GCP_PROJECT=${PROJECT_ID}"
  echo "GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-sa.json"
  echo "ELASTIC_PASSWORD=${ES_PASS}"
} > .env
chmod 600 .env

es_log "Writing GCP SA JSON for Caddy DNS-01"
gcloud secrets versions access latest --secret="${SA_SECRET}" --project="${PROJECT_ID}" > gcp-sa.json
chmod 600 gcp-sa.json

mkdir -p data config logs

cat > docker-compose.es.yml <<EOF
services:
  elasticsearch:
    environment:
      ES_JAVA_OPTS: "${ES_JAVA_OPTS}"
EOF

GHCR_USER=$(curl -fsS --fail -H "Metadata-Flavor: Google" "${META_BASE}/instance/attributes/es_ghcr_username" 2>/dev/null || true)
GHCR_SECRET_ID=$(curl -fsS --fail -H "Metadata-Flavor: Google" "${META_BASE}/instance/attributes/es_ghcr_token_secret_id" 2>/dev/null || true)
if [[ -n "${GHCR_USER}" && -n "${GHCR_SECRET_ID}" ]]; then
  es_log "docker login ghcr.io as ${GHCR_USER}"
  GHCR_PAT="$(gcloud secrets versions access latest --secret="${GHCR_SECRET_ID}" --project="${PROJECT_ID}")"
  printf '%s' "${GHCR_PAT}" | docker login ghcr.io -u "${GHCR_USER}" --password-stdin
fi

es_log "docker compose pull && up -d"
docker compose -f docker-compose.yml -f docker-compose.gcp.yml -f docker-compose.es.yml pull
docker compose -f docker-compose.yml -f docker-compose.gcp.yml -f docker-compose.es.yml up -d

es_log "Done. Elasticsearch HTTPS: https://${CADDY_DOMAIN}/es/"
