apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: trip-service-secrets
  namespace: tripplanning
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: trip-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: tripplanning-db-password
    - secretKey: TRIPPLANNING_AUTH_JWT_SECRET
      remoteRef:
        key: tripplanning-auth-jwt-secret
    - secretKey: ELASTICSEARCH_PASSWORD
      remoteRef:
        key: tbd-es-gateway-elastic-password
    - secretKey: TRIPPLANNING_INTERNAL_SECRET
      remoteRef:
        key: tripplanning-internal-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: social-service-secrets
  namespace: tripplanning
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: social-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: TRIPPLANNING_AUTH_JWT_SECRET
      remoteRef:
        key: tripplanning-auth-jwt-secret
    - secretKey: TRIPPLANNING_INTERNAL_SECRET
      remoteRef:
        key: tripplanning-internal-secret
