apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tripplanning-enterprise-enteentegans
  namespace: tripplanning-ent-enteentegans
  annotations:
    tripplanning.htwg.dev/values-checksum: 278ca9e3f45c647a14dac0acc5032fef6e57658fabf7e24e1a83a79fba277002
spec:
  interval: 10m
  chart:
    spec:
      chart: ms2/charts/tripplanning
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: tripplanning-enterprise-enteentegans-values
      valuesKey: values.yaml
