apiVersion: v1
kind: Namespace
metadata:
  name: tripplanning-ent-enteentegans
  labels:
    app.kubernetes.io/name: tripplanning
    tier: enterprise
    tenant_id: enteentegans
    tripplanning.htwg.dev/tier: enterprise
    tripplanning.htwg.dev/tenant-id: enteentegans
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tripplanning-enterprise-quota
  namespace: tripplanning-ent-enteentegans
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "24"
    limits.memory: 32Gi
    pods: "40"
    persistentvolumeclaims: "5"
