apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-service
  namespace: tripplanning-system
  labels:
    app.kubernetes.io/name: platform-service
    app.kubernetes.io/part-of: tripplanning
  annotations:
    iam.gke.io/gcp-service-account: platform-admin@tbd-cloudappdev.iam.gserviceaccount.com
imagePullSecrets:
  - name: ghcr-pull
