variable "project_id" {}
variable "name_prefix" {}
variable "env_prefix" {}
variable "backend_image" {}
variable "domain_main" {}
variable "domain_api" {}
variable "db_name" {}
variable "frontend_bucket_name" {}
variable "db_password_secret_id" {}
variable "elasticsearch_secret_id" {}
variable "elasticsearch_protocol" {}
variable "elasticsearch_hosts" {}
variable "elasticsearch_username" {}
variable "elasticsearch_path_prefix" {}
variable "search_index_name" {}
variable "firebase_project_id" {}
variable "jwt_secret" {}
variable "image_signer_sa_email" {}
variable "ssl_cert_name" {}
variable "backend_neg_name" {}
variable "enable_dataplex_integration" {}